### Test auth invalid register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "mymail@somedomain.jfjf"
}



### Test auth register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "newuser3",
    "secondName": "second",
    "thirdName": "third",
    "password": "1",
    "email": "mymail@somedomain.jfjf"
}

### Test auth login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "1",
    "email": "mymail@somedomain.jfjf"
}


### Test testuser
GET http://localhost:8080/auth/testuser
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJteW1haWxAc29tZWRvbWFpbi5qZmpmIiwiaXNzIjoiZmFrZXVzbHVnaSIsImlhdCI6MTY1NjUyMjI0NywiZXhwIjoxNjU2NTI1ODQ3fQ.lyZDr6047_Plr9wGlGIjqWKuKUi6H-JkNK7DKD_cwLniwz1ycUH5gFubeOI7T2rYnQaO_CuT0aeBmxbve8MJuA

### Test testuser no auth
GET http://localhost:8080/auth/testuser

### service order with no auth
POST http://localhost:8080/service/order
Content-Type: application/json

{
    "serviceId": 1,
    "userComment": "COMMENT!!!"
}

### service order with auth
POST http://localhost:8080/service/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJteW1haWxAc29tZWRvbWFpbi5qZmpmIiwiaXNzIjoiZmFrZXVzbHVnaSIsImlhdCI6MTY1NjYxNjY4MCwiZXhwIjoxNjU2NjIwMjgwfQ.pbWjR5_WzcKRbuQXop1vhqJxvzYeR-8MnEJZ5l2NnjItR4viV3o18BnOhTFR90rdw5cmTI24_e87UrpiruamPQ

{
    "serviceId": 1,
    "userComment": "COMMENT!!!"
}