### Test auth invalid register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "email": "mymail@somedomain.jfjf"
}



### Test user1 register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "newuser3",
    "secondName": "second",
    "thirdName": "third",
    "password": "1",
    "email": "mymail@somedomain.jfjf"
}

### Test user2 register
POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "name": "newuser6",
    "secondName": "family NAME",
    "thirdName": "petrovich",
    "password": "2",
    "email": "petrovich@james.bond"
}

### Test auth user1 request
# @name auth
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "1",
    "email": "mymail@somedomain.jfjf"
}

### Test auth user2 request
# @name auth
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "password": "2",
    "email": "petrovich@james.bond"
}



### Save Authorization header
@jwt = {{auth.response.headers.Authorization}}


### Test testuser
GET http://localhost:8080/auth/testuser
Authorization: Bearer {{jwt}}

### Test testuser no auth
GET http://localhost:8080/auth/testuser

### service order with no auth
POST http://localhost:8080/service/order
Content-Type: application/json

{
    "serviceId": 1,
    "userComment": "COMMENT!!!"
}

### service order11
POST http://localhost:8080/service/order
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "serviceId": 3,
    "userComment": "no mercy"
}

### service order2
POST http://localhost:8080/service/order
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "serviceId": 2,
    "userComment": "give me"
}

### service order3
POST http://localhost:8080/service/order
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "serviceId": 3,
    "userComment": "want this"
}

### service order with auth id 3
POST http://localhost:8080/service/order
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "serviceId": 3,
    "userComment": "COMMENT!!!"
}

### service list
GET http://localhost:8080/service/list
Content-Type: application/json

### order list
GET http://localhost:8080/service/orders
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Test email
GET http://localhost:8080/testmail